config/routes.rb
Viewcy::Application.routes.draw do
  get '/auth/logout(.:format)', to: 'sessions#destroy', as: :destroy_session
  get '/auth/refresh(.:format)', to: 'sessions#show'
  get '/auth(/:provider)', to: 'sessions#new', as: :new_session
  post '/auth/login(.:format)', to: 'sessions#create', as: :create_session
  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]
  match '/auth/failure', to: 'sessions#failure', via: [ :get, :post ]
  
  namespace :api do
    namespace :v1 do
      resources :schools do
        get 'events(/between/:start(/:end))(.:format)', to: 'events#index', as: :events_between
        post 'affiliations/active', to: 'affiliations#active'
        
        resources :alerts, only: :index

        resources :users do
          resources :appearances
          resources :credits
          
          member do
            post :invite
          end
        end
        
        resources :courses do
          resources :products, only: :index
          resources :appearances
          resources :events, only: :create
        end
        
        resources :appearances
        resources :products

        resources :events, except: :create do
          resources :exclusions, only: :create
          resources :registrations, only: :index
          delete 'exclusions', to: 'exclusions#destroy'
        end
        
        resources :school_attachments, path: 'attachments'
      end

      resources :users, only: :show      
    end
  end

  constraints subdomain: /signup/ do
    resources :school_registrations, path: '', path_names: { new: '' }, only: [ :new, :create ]
  end
  
  constraints subdomain: /.+/ do
    get '/register/regions/:id', as: :registration_regions, to: 'registrations/regions#index'
    get '/register/:event_id/:start', as: :add_registration, to: 'registrations#new'
    post '/register', to: 'registrations#create'
    post '/unregister/:event_id/:start', as: :remove_registration, to: 'registrations#destroy'

    get '/checkout', to: 'orders#show', as: :order
    patch '/checkout', to: 'orders#update', as: :update_order
    scope '/events/:event_id/:start' do
      resources :order_items, shallow: true
    end

    resources :credits, only: :index
    resources :users, only: :create
    
    resources :courses, only: [ :index, :show ] do
      resources :events, only: :index
      namespace :events do
        resources :date_set, only: :index
      end
    end
    
    get '/', to: 'schools#show', as: :school_root
  end
  
  post '/braintree/accept', to: 'braintree#accept'
  resources :reset_passwords
  root to: 'pages#index'
end

app/models/concerns/school_registration/merchant.rb
module SchoolRegistration::Merchant
  extend ActiveSupport::Concern
  
  included do
    cattr_accessor(:merchant_processor) { Braintree::MerchantAccount }
  end
  
  def register_merchant_account!
    result = merchant_processor.create(account_attributes)
    result.success? || begin
      errors[:merchant_account] = result.message
      raise(ActiveRecord::RecordInvalid.new(self))
    end
  end
  
  protected
    def account_attributes
      first_name, last_name = FullNameSplitter.split(user.name)
      
      {
        master_merchant_account_id: '9snyxvf7356cb6kr',
        id: "#{school.identifier}_school",
        individual: {
          first_name: first_name,
          last_name: last_name,
          email: user.email,
          phone: user.phone,
          date_of_birth: user.date_of_birth.to_s,
          ssn: ssn,
          address: {
            street_address: user.billing_address.address,
            locality: user.billing_address.city,
            region: user.billing_address.state,
            postal_code: user.billing_address.zipcode
          }
        },
        business: {
          legal_name: school.legal_name,
          dba_name: school.name,
          tax_id: tax_id,
          address: {
            street_address: school.address.address,
            locality: school.address.city,
            region: school.address.state,
            postal_code: school.address.zipcode
          }
        },
        funding: {
          destination: Braintree::MerchantAccount::FundingDestination::Bank,
          account_number: account_number,
          routing_number: routing_number
        },
        tos_accepted: school.tos_accepted   
      }
    end
end

app/models/school_registration.rb
class SchoolRegistration
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActiveModel::Callbacks
  include SchoolRegistration::Merchant
  
  attr_reader :affiliation
  attr_accessor :ssn, :tax_id, :account_number, :routing_number
  
  class RecordValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      unless value.valid?
        value.errors.each do |key,message|
          record.errors.add("#{attribute}.#{key}", message)
        end
      end
    end
  end
  
  validates :ssn, :tax_id, :account_number, :routing_number, presence: true
  validates :affiliation, record: true
  
  delegate :user, :school, to: :affiliation
  delegate :attributes, :attributes=, to: :user, prefix: true
  delegate :attributes, :attributes=, :identifier, to: :school, prefix: true
  
  def initialize(user, attributes = nil)
    @affiliation = Affiliation.new(user: user, school: School.new, role: Role.owner)
    user.billing_address_required = true
    self.attributes = attributes if attributes
  end
  
  def attributes=(attributes = {})
    attributes.each do |key,value|
      send("#{key}=", value) if respond_to?("#{key}=")
    end
  end
  
  def persisted?
    false
  end
  
  def save!(options = {})
    Affiliation.transaction do
      raise(ActiveRecord::RecordInvalid.new(self)) unless valid?(options)
      affiliation.save!(options)
      register_merchant_account!
    end      
  end
  
  def save(options = {})
    save!(options)
  rescue ActiveRecord::RecordInvalid
    false
  end
end

app/controllers/school_registrations_controller.rb
class SchoolRegistrationsController < ApplicationController
  before_filter :set_user
  
  def new
    @school_registration = SchoolRegistration.new(@user)
  end
  
  def create
    @school_registration = SchoolRegistration.new(@user, school_registration_params)
    
    if @school_registration.save
      redirect_to school_root_url(subdomain: @school_registration.school_identifier)
    else
       render 'new'
    end
  end
  
  private
    def set_user
      @user = current_user || User.new
    end
  
    def school_registration_params
      params.require(:school_registration).permit(
        :ssn, :tax_id, :account_number, :routing_number,
        user_attributes: [
          :name, :email, :date_of_birth, :password,
          billing_address_attributes: [ :address, :address_2, :city, :state, :country, :zipcode ]
        ],
        school_attributes: [
          :name, :legal_name, :identifier, :description, :timezone, :email, :phone,
          :gplus_url, :facebook_url, :twitter_url, :logo_image, :header_image, :tos_accepted,
          address_attributes: [ :address, :address_2, :city, :state, :country, :zipcode ]
        ]
      )
    end
end

app/helpers/school_registrations_helper.rb
module SchoolRegistrationsHelper
  def timezone_options
    ActiveSupport::TimeZone.all.map do |zone|
      [ "#{zone.utc_offset / 3600} #{zone.name}", zone.name ]
    end
  end
end

app/views/school_registrations/new.html.erb
<%= simple_form_for @school_registration, as: :school_registration do |f| %>
	<%= @school_registration.errors[:merchant_account].to_sentence if @school_registration.errors[:merchant_account] %>
	
	<fieldset>
		<legend>
			User Information
		</legend>

		<%= f.fields_for :user_attributes, f.object.user do |u| %>
			<% if f.object.user.new_record? %>
				<%= u.input :name %>
				<%= u.input :email %>
				<%= u.input :password %>
				
				<%= link_to 'Already have an account?', new_session_path %>
			<% end %>
			
			<%= u.input :date_of_birth %>
			<%= f.input :ssn %>		
			
			<%= u.simple_fields_for :billing_address_attributes, u.object.billing_address || Address.new do |a| %>
				<%= a.input :address %>
				<%= a.input :address_2 %>
				<%= a.input :city %>
				<%= a.input :state %>
				<%= a.input :country %>
				<%= a.input :zipcode %>
			<% end %>
		<% end %>
	</fieldset>
	
	<fieldset>
		<legend>
			School Information
		</legend>
	
		<%= f.fields_for :school_attributes, f.object.school do |s| %>
			<%= s.input :name %>
			<%= s.input :legal_name %>
			<%= s.input :identifier %>
			<%= s.input :description %>
			<%= s.input :timezone, collection: timezone_options %>
	
			<%= s.simple_fields_for :address_attributes, s.object.address || Address.new do |a| %>
				<%= a.input :address %>
				<%= a.input :address_2 %>
				<%= a.input :city %>
				<%= a.input :state %>
				<%= a.input :country %>
				<%= a.input :zipcode %>
			<% end %>
	
			<%= s.input :email %>
			<%= s.input :phone %>
			<%= s.input :gplus_url %>
			<%= s.input :facebook_url %>
			<%= s.input :twitter_url %>
	
			<%= s.input :logo_image %>
			<%= s.input :header_image %>	
			<%= s.input :tos_accepted %>
		<% end %>
	</fieldset>
	
	<fieldset>
		<legend>
			Bank Information
		</legend>
		
		<%= f.input :tax_id %>
		<%= f.input :account_number %>
		<%= f.input :routing_number %>
	</fieldset>
	
	<%= f.submit %>	
<% end %>