config/routes.rb
Viewcy::Application.routes.draw do
  get '/auth/logout(.:format)', to: 'sessions#destroy', as: :destroy_session
  get '/auth/refresh(.:format)', to: 'sessions#show'
  get '/auth(/:provider)', to: 'sessions#new', as: :new_session
  post '/auth/login(.:format)', to: 'sessions#create', as: :create_session
  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]
  match '/auth/failure', to: 'sessions#failure', via: [ :get, :post ]
  
  namespace :api do
    namespace :v1 do
      resources :schools do
        get 'events(/between/:start(/:end))(.:format)', to: 'events#index', as: :events_between
        post 'affiliations/active', to: 'affiliations#active'
        
        resources :alerts, only: :index

        resources :users do
          resources :appearances
          resources :credits
          
          member do
            post :invite
          end
        end
        
        resources :courses do
          resources :products, only: :index
          resources :appearances
          resources :events, only: :create
        end
        
        resources :appearances
        resources :products

        resources :events, except: :create do
          resources :exclusions, only: :create
          resources :registrations, only: :index
          delete 'exclusions', to: 'exclusions#destroy'
        end
        
        resources :school_attachments, path: 'attachments'
      end

      resources :users, only: :show      
    end
  end

  constraints subdomain: /signup/ do
    resources :school_registrations, path: '', path_names: { new: '' }, only: [ :new, :create ]
  end
  
  constraints subdomain: /.+/ do
    get '/register/regions/:id', as: :registration_regions, to: 'registrations/regions#index'
    get '/register/:event_id/:start', as: :add_registration, to: 'registrations#new'
    post '/register', to: 'registrations#create'
    post '/unregister/:event_id/:start', as: :remove_registration, to: 'registrations#destroy'

    get '/checkout', to: 'orders#show', as: :order
    patch '/checkout', to: 'orders#update', as: :update_order
    scope '/events/:event_id/:start' do
      resources :order_items, shallow: true
    end

    resources :credits, only: :index
    resources :users, only: :create
    
    resources :courses, only: [ :index, :show ] do
      resources :events, only: :index
      namespace :events do
        resources :date_set, only: :index
      end
    end
    
    get '/', to: 'schools#show', as: :school_root
  end
  
  post '/braintree/accept', to: 'braintree#accept'
  resources :reset_passwords
  root to: 'pages#index'
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  def show
    @user = User.find_by_reset_password_token(params[:id])    
    redirect_to new_reset_password_url unless @user  
  end
  
  def create
    @user = User.find_by_email(params[:email])
    
    if @user
      @user.activate_reset_password_token!
      UserMailer.reset_password(@user).deliver
    else
      render 'new'      
    end
  end
  
  def update
    @user = User.find_by_reset_password_token!(params[:id])    
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]
    @user.reset_password_token = nil
    
    if @user.save
      redirect_to new_session_url
    else
      render 'show'
    end
  end
end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
end

app/views/reset_passwords/create.html.erb
<p>
	Instructions on how to reset your password have been sent to <%= @user.email %>.
</p>

<%# TODO: Remove the following %>
<hr>
<p style="margin: 10px; padding: 20px; border: 5px solid rgba(255, 0, 0, 0.3)">
	<%= link_to reset_password_url(@user.reset_password_token), reset_password_url(@user.reset_password_token) %>
</p>

app/views/reset_passwords/new.html.erb
<% if params[:email].present? %>
	<p>
		<%= params[:email]%> was not found.
	</p>
<% end %>

<%= form_tag reset_passwords_path do %>
	<p>
		<label for="email">
			Your email address
		</label>	
		<%= text_field_tag :email %>
	</p>
	<p>
		<%= submit_tag 'Reset Password' %>
	</p>
<% end %>

app/views/reset_passwords/show.html.erb
<%= form_tag reset_password_path(params[:id]), method: :put do %>
	<p>
		<label for="password">
			New Password
		</label>	
		<%= password_field_tag :password %>
	</p>
	
	<p>
		<label for="password_confirmation">
			Password Confirmation
		</label>	
		<%= password_field_tag :password_confirmation %>
	</p>
	<p>
		<%= submit_tag 'Reset Password' %>
	</p>
<% end %>