config/routes.rb
Viewcy::Application.routes.draw do
  get '/auth/logout(.:format)', to: 'sessions#destroy', as: :destroy_session
  get '/auth/refresh(.:format)', to: 'sessions#show'
  get '/auth(/:provider)', to: 'sessions#new', as: :new_session
  post '/auth/login(.:format)', to: 'sessions#create', as: :create_session
  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]
  match '/auth/failure', to: 'sessions#failure', via: [ :get, :post ]
  
  namespace :api do
    namespace :v1 do
      resources :schools do
        get 'events(/between/:start(/:end))(.:format)', to: 'events#index', as: :events_between
        post 'affiliations/active', to: 'affiliations#active'
        
        resources :alerts, only: :index

        resources :users do
          resources :appearances
          resources :credits
          
          member do
            post :invite
          end
        end
        
        resources :courses do
          resources :products, only: :index
          resources :appearances
          resources :events, only: :create
        end
        
        resources :appearances
        resources :products

        resources :events, except: :create do
          resources :exclusions, only: :create
          resources :registrations, only: :index
          delete 'exclusions', to: 'exclusions#destroy'
        end
        
        resources :school_attachments, path: 'attachments'
      end

      resources :users, only: :show      
    end
  end

  constraints subdomain: /signup/ do
    resources :school_registrations, path: '', path_names: { new: '' }, only: [ :new, :create ]
  end
  
  constraints subdomain: /.+/ do
    get '/register/regions/:id', as: :registration_regions, to: 'registrations/regions#index'
    get '/register/:event_id/:start', as: :add_registration, to: 'registrations#new'
    post '/register', to: 'registrations#create'
    post '/unregister/:event_id/:start', as: :remove_registration, to: 'registrations#destroy'

    get '/checkout', to: 'orders#show', as: :order
    patch '/checkout', to: 'orders#update', as: :update_order
    scope '/events/:event_id/:start' do
      resources :order_items, shallow: true
    end

    resources :credits, only: :index
    resources :users, only: :create
    
    resources :courses, only: [ :index, :show ] do
      resources :events, only: :index
      namespace :events do
        resources :date_set, only: :index
      end
    end
    
    get '/', to: 'schools#show', as: :school_root
  end
  
  post '/braintree/accept', to: 'braintree#accept'
  resources :reset_passwords
  root to: 'pages#index'
end

app/views/layouts/_login.html.erb
<div class="widget">
	<h2>
		Welcome Back.
	</h2>

	<%= form_tag create_session_path do %>
		<p>
			<%= text_field_tag :email, nil, placeholder: 'Email Address' %>
		</p>

		<p>
			<%= password_field_tag :password, nil, placeholder: 'Password' %>
		</p>

		<p>
			<%= icon_button :submit %>
		</p>
	<% end %>

	<nav>
		<%= link_to 'Forgot your password?', new_reset_password_path %>
		<a href="#" data-signup="true" class="createAccount">Create Account</a>
	</nav>
</div>

app/views/layouts/_signup.html.erb
<div class="widget">
	<div class="left">
		<h2>
			Sign Up Today.
		</h2>

		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris rhoncus velit felis, scelerisque cursus urna placerat a. Nullam porta bibendum odio, vel fermentum nunc tristique ut.
		</p>
	
		<nav>
			<a href="#" data-login="true" class="haveAccount">I already have an account</a>
		</nav>
	</div>

	<div class="right">
		<%= render partial: 'users/form', locals: { user: User.new } %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>
			<%= title %>
		</title>
		
	  <%= stylesheet_link_tag "application", media: "all" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/layouts/school.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>
			<%= title %>
		</title>
		
	  <%= stylesheet_link_tag "school", media: "all" %>
	  <%= csrf_meta_tags %>
		<meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
	</head>

	<body>
		<div id="layout">
			<div id="detail">
				<header>
					<div id="authentication">
					</div>
					
					<h1>
						<%= link_to school_root_path do %>
							<% if current_school.logo_image? %>
								<%= image_tag(current_school.logo_image, alt: current_school.name, class: 'logo brand') %>
							<% else %>
								<span class="brand">
									<%= current_school.name %>
								</span>
							<% end %>
						<% end %>
					</h1>
				</header>
					
				<div id="content">
					<%= yield %>
				</div>
			</div>

			<div id="scheduler">
				<%= yield :scheduler %>
			</div>
		</div>
		
		<script>
		data = {
			user: <%= embed_json('api/v1/users/user', current_user, partial: true) %>,
			school: <%= embed_json('schools/show', @school) %>,
			courses: <%= embed_json('courses/index', @courses) %>,
			course: <%= embed_json('courses/show', @course) %>,
		};
		</script>
		<%= javascript_include_tag 'school' %>		
	</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Viewcy</title>
	  <%= stylesheet_link_tag "application", media: "all" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= yield %>
	</body>
</html>